version: '3.8'

networks:
    helios-network:
        driver: bridge

volumes:
    dbdata: ~

services:
    mysql:
        image: mysql:8.0.25
        command: '--default-authentication-plugin=mysql_native_password'
        networks:
            - helios-network
        ports:
            - ${SQL_PORT}:3306
        env_file:
            - .env
        volumes:
            - dbdata:/var/lib/mysql
        healthcheck:
            test: mysqladmin -u root -ptoor status
            interval: 5s
            timeout: 8s
            retries: 30
        cap_add:
            - SYS_NICE

    phpma:
        image: phpmyadmin/phpmyadmin:5.2-fpm-alpine
        depends_on:
            mysql:
                condition: service_healthy
        ports:
            - ${PMA_PORT}:80
        environment:
            PMA_HOST: mysql:3306
            MYSQL_ROOT_PASSWORD: toor
        command:
            - php
            - -S
            - 0.0.0.0:80
            - -t
            - /var/www/html
        volumes:
            -    ./docker/phpmyadmin/docker-entrypoint.sh:/docker-entrypoint.sh
            -    ./docker/phpmyadmin/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            - helios-network

    fpm:
        build:
            context: .
            dockerfile: docker/fpm/Dockerfile
        depends_on:
            mysql:
                condition: service_healthy
        user: ${STDUID:-1000}:${STDGID:-1000}
        ports:
            - ${WEB_PORT}:80
        env_file:
            - .env
        environment:
            HOME: $WORKDIR/.home
            TZ: Europe/Paris
            COMPOSER_HOME: $WORKDIR/.home/.composer
        volumes:
            - ./:$WORKDIR/
            - ./docker/fpm/entrypoint.d:/etc/entrypoint.d
            - ./docker/fpm/date.ini:/usr/local/etc/php/conf.d/date.ini
        working_dir: $WORKDIR
        command:
            - php
            - -S
            - 0.0.0.0:80
            - -t
            - public
        networks:
            - helios-network
